# Generated by Django 6.1.1 on 2026-09-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('descripciom', models.CharField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
